mode = "development"

[bound]
name = "NAME"
endpoint = "ENDPOINT"

[log]
level = "DEBUG"
encoding = "json"

[jwt]
protocol = "PROTOCOL"
private_key = "PRIVATE_KEY"
public_key = "PUBLIC_KEy"

[aws]
region = "AWS_REGION"
access_key_id = "AWS_ACCESS_KEY_ID"
secret_access_key = "AWS_SECRET_ACCESS_KEY"

[rds]
host = "RDS_HOST"
port = "RDS_PORT"
user = "RDS_USER"
password = "RDS_PASSWORD"
database = "RDS_DATABASE"
sslmode = "disable"

[cs]
endpoint = "CS_ENDPOINT"
organization = "CS_ORGANIZATION"
role = "CS_ROLE"