mode = "development"

[bound]
name = "NAME"
endpoint = "ENDPOINT"

[log]
level = "DEBUG"
encoding = "json"

[jwt]
protocol = "PROTOCOL"
private_key = "PRIVATE_KEY"
public_key = "PUBLIC_KEy"

[amazon]
region = "AMAZON_REGION"
access_key = "AMAZON_ACCESS_KEY"
secret_key = "AMAZON_SECRET_KEY"
