mode = "development"

[bound]
name = "BOUND_NAME"
endpoint = "BOUND_ENDPOINT"

[log]
level = "LOG_LEVEL"
encoding = "LOG_ENCODING"

[rsa]
private_key = "RSA_PRIVATE_KEY"

[jwt]
protocol = "JWT_PROTOCOL"
private_key = "JWT_PRIVATE_KEY"
public_key = "JWT_PUBLIC_KEY"

[aws]
region = "AWS_REGION"
ecs_task_role = "AWS_ECS_TASK_ROLE"
secret_create_sleep_time = "AWS_SECRET_CREATE_SLEEP_TIME"

[rds]
host = "RDS_HOST"
port = "RDS_PORT"
user = "RDS_USER"
password = "RDS_PASSWORD"
database = "RDS_DATABASE"
sslmode = "disable"

[cs]
endpoint = "CS_ENDPOINT"
organization = "CS_ORGANIZATION"

[wallet]
max = "WALLET_MAX"

[lambda]
max = "LAMBDA_MAX"
