mode = "development"

[logger]
level = "DEBUG"
encoding = "json"

[jwt]
protocol = "RS256"
private_key = "PRIVATE_KEY"
public_key = "PUBLIC_KEy"

[amazon]
region = "us-east-2"
access_key = "ACCESS_KEY"
secret_key = "SECRET_KEY"
