// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package cs is a generated GoMock package.
package cs

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CubeSignerToken mocks base method.
func (m *MockService) CubeSignerToken(c context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CubeSignerToken", c)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CubeSignerToken indicates an expected call of CubeSignerToken.
func (mr *MockServiceMockRecorder) CubeSignerToken(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CubeSignerToken", reflect.TypeOf((*MockService)(nil).CubeSignerToken), c)
}

// GetSecRole mocks base method.
func (m *MockService) GetSecRole(c context.Context, secret string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecRole", c, secret)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecRole indicates an expected call of GetSecRole.
func (mr *MockServiceMockRecorder) GetSecRole(c, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecRole", reflect.TypeOf((*MockService)(nil).GetSecRole), c, secret)
}
