// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package cs is a generated GoMock package.
package cs

import (
	context "context"
	reflect "reflect"

	dto "github.com/57blocks/auto-action/server/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// ToSign mocks base method.
func (m *MockRepo) ToSign(c context.Context, req *dto.ReqToSign) ([]*dto.RespToSign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToSign", c, req)
	ret0, _ := ret[0].([]*dto.RespToSign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToSign indicates an expected call of ToSign.
func (mr *MockRepoMockRecorder) ToSign(c, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToSign", reflect.TypeOf((*MockRepo)(nil).ToSign), c, req)
}
