// Code generated by MockGen. DO NOT EDIT.
// Source: amazon.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	cloudwatchlogs "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	iam "github.com/aws/aws-sdk-go-v2/service/iam"
	lambda "github.com/aws/aws-sdk-go-v2/service/lambda"
	scheduler "github.com/aws/aws-sdk-go-v2/service/scheduler"
	secretsmanager "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	gomock "github.com/golang/mock/gomock"
)

// MockAmazon is a mock of Amazon interface.
type MockAmazon struct {
	ctrl     *gomock.Controller
	recorder *MockAmazonMockRecorder
}

// MockAmazonMockRecorder is the mock recorder for MockAmazon.
type MockAmazonMockRecorder struct {
	mock *MockAmazon
}

// NewMockAmazon creates a new mock instance.
func NewMockAmazon(ctrl *gomock.Controller) *MockAmazon {
	mock := &MockAmazon{ctrl: ctrl}
	mock.recorder = &MockAmazonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAmazon) EXPECT() *MockAmazonMockRecorder {
	return m.recorder
}

// BoundScheduler mocks base method.
func (m *MockAmazon) BoundScheduler(c context.Context, input *scheduler.CreateScheduleInput, opts ...func(*scheduler.Options)) (*scheduler.CreateScheduleOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{c, input}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BoundScheduler", varargs...)
	ret0, _ := ret[0].(*scheduler.CreateScheduleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BoundScheduler indicates an expected call of BoundScheduler.
func (mr *MockAmazonMockRecorder) BoundScheduler(c, input interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{c, input}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BoundScheduler", reflect.TypeOf((*MockAmazon)(nil).BoundScheduler), varargs...)
}

// CreateRole mocks base method.
func (m *MockAmazon) CreateRole(c context.Context, input *iam.CreateRoleInput) (*iam.CreateRoleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", c, input)
	ret0, _ := ret[0].(*iam.CreateRoleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockAmazonMockRecorder) CreateRole(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockAmazon)(nil).CreateRole), c, input)
}

// CreateSecret mocks base method.
func (m *MockAmazon) CreateSecret(c context.Context, input *secretsmanager.CreateSecretInput) (*secretsmanager.CreateSecretOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", c, input)
	ret0, _ := ret[0].(*secretsmanager.CreateSecretOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockAmazonMockRecorder) CreateSecret(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockAmazon)(nil).CreateSecret), c, input)
}

// DescribeLogStreams mocks base method.
func (m *MockAmazon) DescribeLogStreams(c context.Context, input *cloudwatchlogs.DescribeLogStreamsInput) (*cloudwatchlogs.DescribeLogStreamsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeLogStreams", c, input)
	ret0, _ := ret[0].(*cloudwatchlogs.DescribeLogStreamsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeLogStreams indicates an expected call of DescribeLogStreams.
func (mr *MockAmazonMockRecorder) DescribeLogStreams(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeLogStreams", reflect.TypeOf((*MockAmazon)(nil).DescribeLogStreams), c, input)
}

// GetLogEvents mocks base method.
func (m *MockAmazon) GetLogEvents(c context.Context, input *cloudwatchlogs.GetLogEventsInput) (*cloudwatchlogs.GetLogEventsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogEvents", c, input)
	ret0, _ := ret[0].(*cloudwatchlogs.GetLogEventsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogEvents indicates an expected call of GetLogEvents.
func (mr *MockAmazonMockRecorder) GetLogEvents(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogEvents", reflect.TypeOf((*MockAmazon)(nil).GetLogEvents), c, input)
}

// GetRole mocks base method.
func (m *MockAmazon) GetRole(c context.Context, input *iam.GetRoleInput) (*iam.GetRoleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", c, input)
	ret0, _ := ret[0].(*iam.GetRoleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockAmazonMockRecorder) GetRole(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockAmazon)(nil).GetRole), c, input)
}

// GetScheduler mocks base method.
func (m *MockAmazon) GetScheduler(c context.Context, input *scheduler.GetScheduleInput) (*scheduler.GetScheduleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduler", c, input)
	ret0, _ := ret[0].(*scheduler.GetScheduleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduler indicates an expected call of GetScheduler.
func (mr *MockAmazonMockRecorder) GetScheduler(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduler", reflect.TypeOf((*MockAmazon)(nil).GetScheduler), c, input)
}

// GetSecretValue mocks base method.
func (m *MockAmazon) GetSecretValue(c context.Context, input *secretsmanager.GetSecretValueInput) (*secretsmanager.GetSecretValueOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretValue", c, input)
	ret0, _ := ret[0].(*secretsmanager.GetSecretValueOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretValue indicates an expected call of GetSecretValue.
func (mr *MockAmazonMockRecorder) GetSecretValue(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretValue", reflect.TypeOf((*MockAmazon)(nil).GetSecretValue), c, input)
}

// InvokeLambda mocks base method.
func (m *MockAmazon) InvokeLambda(c context.Context, input *lambda.InvokeInput) (*lambda.InvokeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvokeLambda", c, input)
	ret0, _ := ret[0].(*lambda.InvokeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvokeLambda indicates an expected call of InvokeLambda.
func (mr *MockAmazonMockRecorder) InvokeLambda(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokeLambda", reflect.TypeOf((*MockAmazon)(nil).InvokeLambda), c, input)
}

// PutResourcePolicy mocks base method.
func (m *MockAmazon) PutResourcePolicy(c context.Context, input *secretsmanager.PutResourcePolicyInput) (*secretsmanager.PutResourcePolicyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutResourcePolicy", c, input)
	ret0, _ := ret[0].(*secretsmanager.PutResourcePolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutResourcePolicy indicates an expected call of PutResourcePolicy.
func (mr *MockAmazonMockRecorder) PutResourcePolicy(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutResourcePolicy", reflect.TypeOf((*MockAmazon)(nil).PutResourcePolicy), c, input)
}

// PutRolePolicy mocks base method.
func (m *MockAmazon) PutRolePolicy(c context.Context, input *iam.PutRolePolicyInput) (*iam.PutRolePolicyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutRolePolicy", c, input)
	ret0, _ := ret[0].(*iam.PutRolePolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutRolePolicy indicates an expected call of PutRolePolicy.
func (mr *MockAmazonMockRecorder) PutRolePolicy(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutRolePolicy", reflect.TypeOf((*MockAmazon)(nil).PutRolePolicy), c, input)
}

// RegisterLambda mocks base method.
func (m *MockAmazon) RegisterLambda(c context.Context, input *lambda.CreateFunctionInput, opts ...func(*lambda.Options)) (*lambda.CreateFunctionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{c, input}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterLambda", varargs...)
	ret0, _ := ret[0].(*lambda.CreateFunctionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterLambda indicates an expected call of RegisterLambda.
func (mr *MockAmazonMockRecorder) RegisterLambda(c, input interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{c, input}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterLambda", reflect.TypeOf((*MockAmazon)(nil).RegisterLambda), varargs...)
}

// RemoveLambda mocks base method.
func (m *MockAmazon) RemoveLambda(c context.Context, input *lambda.DeleteFunctionInput) (*lambda.DeleteFunctionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLambda", c, input)
	ret0, _ := ret[0].(*lambda.DeleteFunctionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveLambda indicates an expected call of RemoveLambda.
func (mr *MockAmazonMockRecorder) RemoveLambda(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLambda", reflect.TypeOf((*MockAmazon)(nil).RemoveLambda), c, input)
}

// RemoveScheduler mocks base method.
func (m *MockAmazon) RemoveScheduler(c context.Context, input *scheduler.DeleteScheduleInput) (*scheduler.DeleteScheduleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveScheduler", c, input)
	ret0, _ := ret[0].(*scheduler.DeleteScheduleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveScheduler indicates an expected call of RemoveScheduler.
func (mr *MockAmazonMockRecorder) RemoveScheduler(c, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveScheduler", reflect.TypeOf((*MockAmazon)(nil).RemoveScheduler), c, input)
}
