// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	dto "github.com/57blocks/auto-action/server/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockOAuthService is a mock of OAuthService interface.
type MockOAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthServiceMockRecorder
}

// MockOAuthServiceMockRecorder is the mock recorder for MockOAuthService.
type MockOAuthServiceMockRecorder struct {
	mock *MockOAuthService
}

// NewMockOAuthService creates a new mock instance.
func NewMockOAuthService(ctrl *gomock.Controller) *MockOAuthService {
	mock := &MockOAuthService{ctrl: ctrl}
	mock.recorder = &MockOAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthService) EXPECT() *MockOAuthServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockOAuthService) Login(c context.Context, req dto.ReqLogin) (*dto.RespCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", c, req)
	ret0, _ := ret[0].(*dto.RespCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockOAuthServiceMockRecorder) Login(c, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockOAuthService)(nil).Login), c, req)
}

// Logout mocks base method.
func (m *MockOAuthService) Logout(c context.Context, raw string) (*dto.RespLogout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", c, raw)
	ret0, _ := ret[0].(*dto.RespLogout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockOAuthServiceMockRecorder) Logout(c, raw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockOAuthService)(nil).Logout), c, raw)
}

// Refresh mocks base method.
func (m *MockOAuthService) Refresh(c context.Context, raw string) (*dto.RespCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", c, raw)
	ret0, _ := ret[0].(*dto.RespCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockOAuthServiceMockRecorder) Refresh(c, raw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockOAuthService)(nil).Refresh), c, raw)
}

// Signup mocks base method.
func (m *MockOAuthService) Signup(c context.Context, req dto.ReqSignup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", c, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signup indicates an expected call of Signup.
func (mr *MockOAuthServiceMockRecorder) Signup(c, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockOAuthService)(nil).Signup), c, req)
}
