// Code generated by MockGen. DO NOT EDIT.
// Source: cs.go

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	reflect "reflect"

	model "github.com/57blocks/auto-action/server/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockCubeSigner is a mock of CubeSigner interface.
type MockCubeSigner struct {
	ctrl     *gomock.Controller
	recorder *MockCubeSignerMockRecorder
}

// MockCubeSignerMockRecorder is the mock recorder for MockCubeSigner.
type MockCubeSignerMockRecorder struct {
	mock *MockCubeSigner
}

// NewMockCubeSigner creates a new mock instance.
func NewMockCubeSigner(ctrl *gomock.Controller) *MockCubeSigner {
	mock := &MockCubeSigner{ctrl: ctrl}
	mock.recorder = &MockCubeSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCubeSigner) EXPECT() *MockCubeSignerMockRecorder {
	return m.recorder
}

// DeleteCSKey mocks base method.
func (m *MockCubeSigner) DeleteCSKey(c context.Context, key string, accountId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCSKey", c, key, accountId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCSKey indicates an expected call of DeleteCSKey.
func (mr *MockCubeSignerMockRecorder) DeleteCSKey(c, key, accountId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCSKey", reflect.TypeOf((*MockCubeSigner)(nil).DeleteCSKey), c, key, accountId)
}

// FindCSKey mocks base method.
func (m *MockCubeSigner) FindCSKey(c context.Context, key string, accountId uint64) (*model.CubeSignerKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCSKey", c, key, accountId)
	ret0, _ := ret[0].(*model.CubeSignerKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCSKey indicates an expected call of FindCSKey.
func (mr *MockCubeSignerMockRecorder) FindCSKey(c, key, accountId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCSKey", reflect.TypeOf((*MockCubeSigner)(nil).FindCSKey), c, key, accountId)
}

// FindCSKeysByAccount mocks base method.
func (m *MockCubeSigner) FindCSKeysByAccount(c context.Context, accountId uint64) ([]*model.CubeSignerKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCSKeysByAccount", c, accountId)
	ret0, _ := ret[0].([]*model.CubeSignerKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCSKeysByAccount indicates an expected call of FindCSKeysByAccount.
func (mr *MockCubeSignerMockRecorder) FindCSKeysByAccount(c, accountId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCSKeysByAccount", reflect.TypeOf((*MockCubeSigner)(nil).FindCSKeysByAccount), c, accountId)
}

// SyncCSKey mocks base method.
func (m *MockCubeSigner) SyncCSKey(c context.Context, key *model.CubeSignerKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncCSKey", c, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncCSKey indicates an expected call of SyncCSKey.
func (mr *MockCubeSignerMockRecorder) SyncCSKey(c, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncCSKey", reflect.TypeOf((*MockCubeSigner)(nil).SyncCSKey), c, key)
}
