name: Build Cross-Platform CLI Tool

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22]  # 根据需要选择 Go 版本
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-latest
            arch: amd64
          - os: ubuntu-latest
            arch: amd64
          - os: windows-latest
            arch: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: |
          GOOS=${{ matrix.os == 'ubuntu-latest' && 'linux' || (matrix.os == 'macos-latest' && 'darwin' || 'windows') }}
          GOARCH=${{ matrix.arch }}
          mkdir -p output/$GOOS/$GOARCH
          go build -o output/$GOOS/$GOARCH/myapp-$GOOS-$GOARCH${{ GOOS == 'windows' && '.exe' || '' }}
        env:
          GO111MODULE: "on"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-binaries
          path: output/
