name: Compile Cross-Platform CLI

on:
  push:
    paths:
      - "cli/**"
    tags:
      - "*"

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version:
          - 1.22
        os:
          - linux
          - darwin
          - windows
        arch:
          - amd64
          - arm64
        exclude:
          - os: windows
            arch: arm64
          - os: linux
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: |
          cd cli
          GOOS=${{ matrix.os == 'linux' || (matrix.os == 'darwin' || 'windows') }}
          GOARCH=${{ matrix.arch }}
          output_path=./output/
          file_name=st3llar-$GOOS-$GOARCH${{ matrix.os == 'windows' && '.exe' || '' }}
          mkdir -p "$output_path"
          go build -o "$output_path/$file_name"

        env:
          GO111MODULE: "on"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cross-platform binaries
          path: ./cli/output/
          overwrite: true # Optional. Default is 'false'
          if-no-files-found: error # Optional. Default is 'warn'
          retention-days: 1 # Optional. Defaults to repository settings.
          # 0: No compression
          # 1: Best speed
          # 6: Default compression (same as GNU Gzip)
          # 9: Best compression
          compression-level: 0
