name: Compile CLI And Publish

on:
  push:
    paths:
      - "cli/**"
    tags:
      - "*"
  workflow_dispatch:

jobs:
  compile:
    runs-on: ${{ matrix.os.runner }}

    strategy:
      matrix:
        go:
          - 1.22
        os:
          - name: linux
            runner: ubuntu-latest
          - name: darwin
            runner: macos-latest
          - name: windows
            runner: windows-latest
        arch:
          - amd64
          - arm64
        exclude:
          - os:
              name: linux
            arch: arm64
          - os:
              name: windows
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build ${{ matrix.os.name }} ${{ matrix.arch }}
        if: matrix.os.name != 'windows'
        env:
          GO111MODULE: "on"
          GOOS: ${{ matrix.os.name }}
          GOARCH: ${{ matrix.arch }}
        run: |
          cd cli
          go build -o "autoaction-${{ matrix.os.name }}-${{ matrix.arch }}"

      - name: Build windows amd64
        if: matrix.os.name == 'windows'
        env:
          GO111MODULE: "on"
          GOOS: ${{ matrix.os.name }}
          GOARCH: ${{ matrix.arch }}
        run: |
          cd cli
          go build -o "autoaction-${{ matrix.os.name }}-${{ matrix.arch }}.exe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autoaction-${{ matrix.os.name }}-${{ matrix.arch }}
          path: ./cli/autoaction-${{ matrix.os.name }}-${{ matrix.arch }}${{ matrix.os.name == 'windows' && '.exe' || '' }}
          overwrite: true # Optional. Default is 'false'
          if-no-files-found: error # Optional. Default is 'warn'
          retention-days: 1 # Optional. Defaults to repository settings.
          # 0: No compression
          # 1: Best speed
          # 6: Default compression (same as GNU Gzip)
          # 9: Best compression
          compression-level: 0
  release:
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'autoaction-darwin-arm64'
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          # get upload url and remove the {?name,label} at the end
          upload_url="${{ steps.create_release.outputs.upload_url }}"
          upload_url="${upload_url%\{*}"
          
          # iterate over all downloaded files and upload
          for file in ./artifacts/**/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              echo "Uploading $filename to release..."
              curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/octet-stream" \
                --data-binary @"$file" \
                "${upload_url}?name=${filename}"
            fi
          done
