name: HomeBrew/Chocolatey Publish

on:
  workflow_run:
    workflows:
      - "Compile Cross-Platform CLI"
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        run: |
          # get upload url and remove the {?name,label} at the end
          upload_url="${{ steps.create_release.outputs.upload_url }}"
          upload_url="${upload_url%\{*}"
          
          # iterate over all downloaded files and upload
          for file in ./artifacts/**/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              echo "Uploading $filename to release..."
              curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/octet-stream" \
                --data-binary @"$file" \
                "${upload_url}?name=${filename}"
            fi
          done